{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aegis.fullname" . }}-secrets
  labels:
    {{- include "aegis.labels" . | nindent 4 }}
type: Opaque
data:
  admin-secret: {{ required "secrets.adminSecret is required when secrets.existingSecret is not set" .Values.secrets.adminSecret | b64enc | quote }}
  redis-password: {{ required "secrets.redisPassword is required when secrets.existingSecret is not set" .Values.secrets.redisPassword | b64enc | quote }}
  {{- if .Values.secrets.jwtSecret }}
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.forensicDsn }}
  forensic-dsn: {{ .Values.secrets.forensicDsn | b64enc | quote }}
  {{- end }}
{{- end }}
