apiVersion: v1
kind: Service
metadata:
  name: {{ include "aegis.fullname" . }}
  labels:
    {{- include "aegis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.gatewayPort }}
      targetPort: gateway
      protocol: TCP
      name: gateway
    - port: {{ .Values.service.adminPort }}
      targetPort: admin
      protocol: TCP
      name: admin
  selector:
    {{- include "aegis.selectorLabels" . | nindent 4 }}
